//
// Autogenerated by Thrift Compiler (0.13.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import Int64 = require('node-int64');


export declare class SinglePrompt {
  request_id: string;
  prompt: string;

    constructor(args?: { request_id: string; prompt?: string; });
}

export declare class GenerationConfig {
  num_beams: number;
  do_sample: boolean;
  temperature: number;
  top_p: number;
  top_k: number;
  max_new_tokens: number;
  repetition_penalty: number;
  length_penalty: number;

    constructor(args?: { num_beams?: number; do_sample?: boolean; temperature?: number; top_p?: number; top_k?: number; max_new_tokens?: number; repetition_penalty?: number; length_penalty?: number; });
}
