//
// Autogenerated by Thrift Compiler (0.13.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import Int64 = require('node-int64');


export declare class ApiSinglePromptRequest {
  request_id: string;
  prompt: string;
  stream_response: boolean;
  only_new_tokens: boolean;
  generation_config: GenerationConfig;

    constructor(args?: { request_id: string; prompt?: string; stream_response?: boolean; only_new_tokens?: boolean; generation_config?: GenerationConfig; });
}

export declare class ApiSinglePromptStream {
  text: string;

    constructor(args?: { text: string; });
}

export declare class ApiBatchPromptRequest {
  prompts: SinglePrompt[];
  only_new_tokens: boolean;
  generation_config: GenerationConfig;

    constructor(args?: { prompts: SinglePrompt[]; only_new_tokens?: boolean; generation_config?: GenerationConfig; });
}

export declare class ApiBatchPrompt {
  request_id: string;
  prompt: string;
  response: string;

    constructor(args?: { request_id: string; prompt?: string; response: string; });
}

export declare class ApiBatchPromptResponse {
  responses: ApiBatchPrompt[];

    constructor(args?: { responses: ApiBatchPrompt[]; });
}
