//
// Autogenerated by Thrift Compiler (0.13.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import Int64 = require('node-int64');


export declare class MilvusSegmentGetRequest {
  search: string;
  document_ids: string[];
  offset: number;
  limit: number;
  sf: number;

    constructor(args?: { search: string; document_ids?: string[]; offset?: number; limit?: number; sf?: number; });
}

export declare class MilvusSegmentUpsertPayload {
  segment_text: string;
  document_id: string;
  section_id: string;
  segment_id: string;

    constructor(args?: { segment_text: string; document_id: string; section_id: string; segment_id: string; });
}

export declare class MilvusSegmentDeletePayload {
  document_id: string;
  section_id: string;
  segment_id: string;

    constructor(args?: { document_id: string; section_id: string; segment_id: string; });
}

export declare class L2SegmentSearchResult {
  distance: number;
  document_id: string;
  section_id: string;
  segment_id: string;

    constructor(args?: { distance: number; document_id: string; section_id: string; segment_id: string; });
}

export declare class L2SegmentSearchResponse {
  results: L2SegmentSearchResult[];
  total: number;
  is_error: boolean;
  error_text: string;

    constructor(args?: { results: L2SegmentSearchResult[]; total: number; is_error: boolean; error_text?: string; });
}

export declare class L2SegmentUpsertResponse {
  insert_count: number;
  update_count: number;
  delete_count: number;
  is_error: boolean;
  error_text: string;

    constructor(args?: { insert_count: number; update_count: number; delete_count: number; is_error: boolean; error_text?: string; });
}

export declare class L2SegmentDeleteResponse {
  delete_count: number;
  is_error: boolean;
  error_text: string;

    constructor(args?: { delete_count: number; is_error: boolean; error_text?: string; });
}
