name: Sync thrift changes to types repository

on:
  push:
    branches:
      - dev
    paths:
      - "test/**"
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.TYPES_REPO_TOKEN }}
  
      # Step to clone the specific repo, copy the thrift folder and specific files
      - name: Clone, copy thrift folder, and include specific files
        run: |
          # Clone the external repository
          git clone https://github.com/alexandriaproject-io/llm-inference.git

          # Create the destination folder
          mkdir -p llm-inference-thrift

          # Copy the thrift directory and specific files into the llm-inference-thrift folder
          cp -r llm-inference/thrift llm-inference-thrift/thrift
          cp llm-inference/thrift_build.ps1 llm-inference-thrift/thrift_build.ps1
          cp llm-inference/thrift_build.sh llm-inference-thrift/thrift_build.sh

          # Remove the cloned repository to clean up
          rm -rf llm-inference

      - name: Install Thrift Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y thrift-compiler

      # Assuming thrift_build.sh is inside llm-inference-thrift and it generates com and html directories
      - name: Setup and run thrift build script
        run: |
          cd llm-inference-thrift
          chmod +x thrift_build.sh
          mkdir -p html
          bash -c "./thrift_build.sh"
      # Copy the generated directories to thrift-output
      - name: Copy generated directories
        run: |
          mkdir -p ./thrift-output
          cp -r ./llm-inference-thrift/com ./thrift-output/
          cp -r ./llm-inference-thrift/html ./thrift-output/

      # Remove the llm-inference-thrift directory
      - name: Remove llm-inference-thrift directory
        run: rm -rf llm-inference-thrift


      # Optional: Commit and push the changes to the current repository
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global pull.rebase true

          git add thrift-output/
          git commit -m "Include llm-inference thrift folder and build scripts" || echo "No changes to commit"
    
          git tag -a "v$(date +'%Y%m%d%H%M%S')" -m "Automated build tag"
          
          git push origin HEAD:dev --tags

      # - name: Commit and Push Build
      #   run: |
      #     git config --global user.name 'github-actions[bot]'
      #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      #     git add -f build/
      #     git commit -m "Automated build commit" || echo "No changes to commit"
      #     git tag -a "v$(date +'%Y%m%d%H%M%S')" -m "Automated build tag"
      #     git pull
      #     git push --tags
      #     git fetch origin dev
      #     git push --force-with-lease origin HEAD:dev
