name: Sync thrift changes to types repository

on:
  push:
    branches:
      - dev
    paths:
      - "test/**"
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.TYPES_REPO_TOKEN }}

      - name: Clone, copy thrift folder, and include specific files
        env:
          REPO_NAME: llm-inference
        run: |
          git clone https://github.com/alexandriaproject-io/${{ REPO_NAME }}.git
          cd ${{ REPO_NAME }}
          git checkout dev
          cd ..
          
          mkdir -p ${{ REPO_NAME }}-thrift
          cp -r ${{ REPO_NAME }}/thrift ${{ REPO_NAME }}-thrift/thrift
          cp ${{ REPO_NAME }}/thrift_build.sh ${{ REPO_NAME }}-thrift/thrift_build.sh

          rm -rf ${{ REPO_NAME }}

      - name: Install Thrift Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y thrift-compiler

      - name: Setup and run thrift build script
        env:
          REPO_NAME: llm-inference
        run: |
          cd ${{ REPO_NAME }}-thrift
          chmod +x thrift_build.sh
          bash -c "./thrift_build.sh --py ./build/${{ REPO_NAME }}/python"
          bash -c "./thrift_build.sh --html ./build/${{ REPO_NAME }}/html"
          bash -c "./thrift_build.sh --golang ./build/${{ REPO_NAME }}/golang"
          bash -c "./thrift_build.sh --ts ./build/${{ REPO_NAME }}/ts"

          cp -r ./${{ REPO_NAME }}-thrift/build ./
          rm -rf ${{ REPO_NAME }}-thrift

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global pull.rebase true

          git add .
          git commit -m "Updated thrift interfaces"
          
          git tag -a "v$(date +'%Y%m%d%H%M%S')" -m "Automated build tag"
          git push origin HEAD:dev --tags
